## ANN Regression
#### Predict the salary of customers on churn data

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
## Load the data
data = pd.read_csv("../Datasets/Churn_Modelling.csv")

print(data.shape)
data.head()

(10000, 14)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
## Preprocess the data
data = data.drop(columns=["RowNumber", "CustomerId", "Surname"])

data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## Encode categorical variable
le_gender = LabelEncoder()
data['Gender'] = le_gender.fit_transform(data['Gender'])

data['Gender']

0       0
1       0
2       0
3       0
4       0
       ..
9995    1
9996    1
9997    0
9998    1
9999    0
Name: Gender, Length: 10000, dtype: int64

In [5]:
## Encode geography cols
ohe_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = ohe_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=ohe_geo.get_feature_names_out(input_features=['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [6]:
## Combine ohe encoded column with the original data
data = pd.concat([data.drop(columns=['Geography']), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [7]:
## Split the data into features and target
X = data.drop(columns=["EstimatedSalary"])
y = data["EstimatedSalary"]

In [8]:
X.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,0,0.0,0.0,1.0

In [9]:
## Train test split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(8000, 12) (2000, 12) (8000,) (2000,)

In [10]:
## Scale the train and test features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_train_scaled

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [11]:
## Save encoder, scaler as pickle file
with open(file="../artifacts/gender_le_reg.pkl", mode='wb') as file:
    pickle.dump(obj=le_gender, file=file)

with open(file="../artifacts/geo_ohe_reg.pkl", mode='wb') as file:
    pickle.dump(obj=ohe_geo, file=file)

with open(file="../artifacts/scaler_reg.pkl", mode='wb') as file:
    pickle.dump(obj=scaler, file=file)

## ANN Implementation for Regression

In [12]:
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense

In [13]:
## ANN Architecuter
model = Sequential([
    Dense(units=64, activation='relu', input_dim=X_train_scaled.shape[1]),
    Dense(32, activation='relu'),
    Dense(1)    # output layer (default activation linear_activation)
])

model.summary()

e:\AI\03 - Deep Learning\Deep-Learning-Projects\ANN\Churn-Modelling\churn_venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
## Compile the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [15]:
## Setup for Train the model
from keras.callbacks import EarlyStopping, TensorBoard
import datetime

## Setup tensorboard
log_dir = "../regressionlog/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [16]:
## Setup early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [17]:
## Train the model
history = model.fit(
    X_train_scaled, y_train,
    validation_data=(X_test_scaled, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 100346.8125 - mae: 100346.8125 - val_loss: 98410.5234 - val_mae: 98410.5234
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99290.1953 - mae: 99290.1953 - val_loss: 96322.1719 - val_mae: 96322.1719
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 95729.9922 - mae: 95729.9922 - val_loss: 91169.7500 - val_mae: 91169.7500
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 88951.1016 - mae: 88951.1016 - val_loss: 82907.5547 - val_mae: 82907.5547
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 79456.3125 - mae: 79456.3125 - val_loss: 72807.8906 - val_mae: 72807.8906
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 69062.4922 - mae: 69062.4922 - val_loss: 63309.7148 - val_mae: 63309.7148
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 60174.4023 - mae: 60174.4023 - val_loss: 56261.7031 - val_mae: 56261.7031
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 54507.3828 - mae: 54507.3828 - val_loss: 52537.5977 - val_mae: 52537.5977
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 51702.6016 - mae: 51702.6016 - val_loss: 51109.5312 - val_mae: 51109.5312
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50628.6914 - mae: 50628.6914 - val_loss: 50724.4141 - val_mae: 50724.4141
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50256.3711 - mae: 50256.3711 - val_loss: 50608.7461 - val_mae: 50608.7461
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50100.6289 - mae: 50100.6289 - val_loss: 50570.9258 - val_mae: 50570.9258
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50022.0547 - mae: 50022.0547 - val_loss: 50539.2773 - val_mae: 50539.2773
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49971.2812 - mae: 49971.2812 - val_loss: 50506.2617 - val_mae: 50506.2617
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49929.2891 - mae: 49929.2891 - val_loss: 50484.3438 - val_mae: 50484.3438
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49891.0273 - mae: 49891.0273 - val_loss: 50464.6523 - val_mae: 50464.6523
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49857.0234 - mae: 49857.0234 - val_loss: 50454.7305 - val_mae: 50454.7305
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49827.7773 - mae: 49827.7773 - val_loss: 50442.1914 - val_mae: 50442.1914
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49799.7109 - mae: 49799.7109 - val_loss: 50426.3359 - val_mae: 50426.3359
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49774.7148 - mae: 49774.7148 - val_loss: 50420.7031 - val_mae: 50420.7031
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49752.8789 - mae: 49752.8789 - val_loss: 50405.3984 - val_mae: 50405.3984
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49736.7422 - mae: 49736.7422 - val_loss: 50391.7188 - val_mae: 50391.7188
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49715.3984 - mae: 49715.3984 - val_loss: 50390.3750 - val_mae: 50390.3750
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49695.2227 - mae: 49695.2227 - val_loss: 50390.1641 - val_mae: 50390.1641
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49677.3672 - mae: 49677.3672 - val_loss: 50373.6602 - val_mae: 50373.6602
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49662.6445 - mae: 49662.6445 - val_loss: 50371.5078 - val_mae: 50371.5078
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49644.6797 - mae: 49644.6797 - val_loss: 50361.4570 - val_mae: 50361.4570
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49630.8438 - mae: 49630.8438 - val_loss: 50359.9023 - val_mae: 50359.9023
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49616.8438 - mae: 49616.8438 - val_loss: 50368.4141 - val_mae: 50368.4141
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49603.4102 - mae: 49603.4102 - val_loss: 50374.3359 - val_mae: 50374.3359
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49588.6367 - mae: 49588.6367 - val_loss: 50362.2148 - val_mae: 50362.2148
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49579.6836 - mae: 49579.6836 - val_loss: 50374.0977 - val_mae: 50374.0977
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49563.2148 - mae: 49563.2148 - val_loss: 50359.4727 - val_mae: 50359.4727
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49552.6133 - mae: 49552.6133 - val_loss: 50368.8008 - val_mae: 50368.8008
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49541.8281 - mae: 49541.8281 - val_loss: 50372.9102 - val_mae: 50372.9102
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49531.7305 - mae: 49531.7305 - val_loss: 50376.2227 - val_mae: 50376.2227
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49524.1523 - mae: 49524.1523 - val_loss: 50368.0703 - val_mae: 50368.0703
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49510.3711 - mae: 49510.3711 - val_loss: 50366.7734 - val_mae: 50366.7734
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49503.0156 - mae: 49503.0156 - val_loss: 50376.4766 - val_mae: 50376.4766
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49494.4883 - mae: 49494.4883 - val_loss: 50352.2461 - val_mae: 50352.2461
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49489.5156 - mae: 49489.5156 - val_loss: 50351.2305 - val_mae: 50351.2305
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49478.6250 - mae: 49478.6250 - val_loss: 50359.9414 - val_mae: 50359.9414
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49472.2812 - mae: 49472.2812 - val_loss: 50348.1836 - val_mae: 50348.1836
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49462.5352 - mae: 49462.5352 - val_loss: 50355.1562 - val_mae: 50355.1562
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49458.1914 - mae: 49458.1914 - val_loss: 50351.4023 - val_mae: 50351.4023
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49449.6211 - mae: 49449.6211 - val_loss: 50350.6758 - val_mae: 50350.6758
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49442.9648 - mae: 49442.9648 - val_loss: 50356.3008 - val_mae: 50356.3008
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49432.7617 - mae: 49432.7617 - val_loss: 50362.2109 - val_mae: 50362.2109
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49429.8047 - mae: 49429.8047 - val_loss: 50368.1250 - val_mae: 50368.1250
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49423.1445 - mae: 49423.1445 - val_loss: 50364.5977 - val_mae: 50364.5977
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49417.7656 - mae: 49417.7656 - val_loss: 50357.6797 - val_mae: 50357.6797
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49411.1133 - mae: 49411.1133 - val_loss: 50350.6016 - val_mae: 50350.6016
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49404.6680 - mae: 49404.6680 - val_loss: 50358.8203 - val_mae: 50358.8203

### Evaluate the model

In [19]:
## Load the Tensorboard Extension
%load_ext tensorboard

## It is a Jupyter/IPython magic command that loads the TensorBoard notebook extension into the current notebook session.

In [20]:
## Now opens the TensorBoard dashboard for the log folder
%tensorboard --logdir ../regressionlog/fit

## See the output of this cell in the browser "http://localhost:6006"

## Stop the process
# !tasklist | findstr "tensorboard"
# !taskkill /F /PID <PID>

#### Stop the process (tensorboard)

In [21]:
!tasklist | findstr "tensorboard"

tensorboard.exe              28512 Console                    3      5,384 K

In [22]:
!taskkill /F /PID 28512

SUCCESS: The process with PID 28512 has been terminated.

#### Evaluate model on the test data

In [25]:
test_loss, test_mae = model.evaluate(X_test_scaled, y_test)
print(f"Test MAE : {test_mae: .4f}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 50348.1836 - mae: 50348.1836
Test MAE :  50348.1836

In [26]:
## Save the model
model.save("../artifacts/reg_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.